<script setup>
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { faUser } from '@fortawesome/free-solid-svg-icons/faUser'
import { faImage } from '@fortawesome/free-solid-svg-icons/faImage'
import { faPalette } from '@fortawesome/free-solid-svg-icons/faPalette'
import { faLink } from '@fortawesome/free-solid-svg-icons/faLink'
import { faPlus } from '@fortawesome/free-solid-svg-icons/faPlus'
import { faPen } from '@fortawesome/free-solid-svg-icons/faPen'
import { faTrash } from '@fortawesome/free-solid-svg-icons/faTrash'
import { faArrowUp } from '@fortawesome/free-solid-svg-icons/faArrowUp'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons/faArrowDown'
import { faWandMagicSparkles } from '@fortawesome/free-solid-svg-icons/faWandMagicSparkles'
import { faEye } from '@fortawesome/free-solid-svg-icons/faEye'
import { faCloudArrowUp } from '@fortawesome/free-solid-svg-icons/faCloudArrowUp'
import { faCopy } from '@fortawesome/free-solid-svg-icons/faCopy'
import { faDownload } from '@fortawesome/free-solid-svg-icons/faDownload'
import { faMobileScreen } from '@fortawesome/free-solid-svg-icons/faMobileScreen'
import { faDesktop } from '@fortawesome/free-solid-svg-icons/faDesktop'
import { faRotateLeft } from '@fortawesome/free-solid-svg-icons/faRotateLeft'
import { faCheck } from '@fortawesome/free-solid-svg-icons/faCheck'
import { faChevronRight } from '@fortawesome/free-solid-svg-icons/faChevronRight'
import { faLocationDot } from '@fortawesome/free-solid-svg-icons/faLocationDot'
import { faGlobe } from '@fortawesome/free-solid-svg-icons/faGlobe'
import { faPhone } from '@fortawesome/free-solid-svg-icons/faPhone'
import { faEnvelope } from '@fortawesome/free-solid-svg-icons/faEnvelope'
import { faQrcode } from '@fortawesome/free-solid-svg-icons/faQrcode'
import { faHouse } from '@fortawesome/free-solid-svg-icons/faHouse'
import { faChartSimple } from '@fortawesome/free-solid-svg-icons/faChartSimple'
import { faGear } from '@fortawesome/free-solid-svg-icons/faGear'
import { faGripVertical } from '@fortawesome/free-solid-svg-icons/faGripVertical'
import { faWhatsapp } from '@fortawesome/free-brands-svg-icons/faWhatsapp'
import { faInstagram } from '@fortawesome/free-brands-svg-icons/faInstagram'
import { faFacebook } from '@fortawesome/free-brands-svg-icons/faFacebook'
import { faTiktok } from '@fortawesome/free-brands-svg-icons/faTiktok'
import { faGithub } from '@fortawesome/free-brands-svg-icons/faGithub'
import { faLinkedin } from '@fortawesome/free-brands-svg-icons/faLinkedin'
defineProps({ name: String })
const icons = { user: faUser, image: faImage, palette: faPalette, link: faLink, plus: faPlus, edit: faPen, delete: faTrash, up: faArrowUp, down: faArrowDown, ai: faWandMagicSparkles, eye: faEye, upload: faCloudArrowUp, copy: faCopy, download: faDownload, mobile: faMobileScreen, desktop: faDesktop, reset: faRotateLeft, check: faCheck, next: faChevronRight, maps: faLocationDot, website: faGlobe, phone: faPhone, email: faEnvelope, qr: faQrcode, home: faHouse, analytics: faChartSimple, settings: faGear, grip: faGripVertical, whatsapp: faWhatsapp, instagram: faInstagram, facebook: faFacebook, tiktok: faTiktok, github: faGithub, linkedin: faLinkedin }
</script>
<template><FontAwesomeIcon :icon="icons[name] || faLink" aria-hidden="true" /></template>
